### ISSUE TITLE
Bugsplat option is not available on Edit context menu

### ISSUE THREAD

**Issue by shehan-mark** [BugSplat-Git/bugsplat-unreal#26]
I've tried this plugin by putting the content of this repo into the `Plugins/Bugsplat` of my project's directory. But after running the Editor the Bugsplat menu item is not visible in the Edit context menu of the Editor.

I got the following error in my logs if that helps.

```
Error: Package {Project}/Plugins/BugSplat/Content/UI/W_BugSplatButton.uasset has newer custom version of FortniteMain
Error: Package {Project}/Plugins/BugSplat/Content/UI/W_BugSplatDemo.uasset has newer custom version of FortniteMain
```

Environment -

* Customized version of UE 4.26.1
* VS 2019
* Win 10

What I've tried - 
I tried to add these assets manually into the engine content folder but couldn't add. But when I tried that with UE 4.27 I could add it to the Content folder in the editor. So I opened these two blueprints using 4.27 and created duplicates of these two assets using our customized UE 4.26. And tried replacing `{Project}/Plugins/BugSplat/Content/UI/W_BugSplatButton.uasset` and `{Project}/Plugins/BugSplat/Content/UI/W_BugSplatDemo.uasset` with the newer ones I created using 4.26. But when I start the UE 4.26.1 again I get the above error.

Any clue on whats going on ?

**Comment by bobbyg603** [comment]
Hi @shehan-mark we just pushed a big update here and have not updated the documentation yet. The BugSplat options can now be found in the project settings menu. All of the same controls should be there, plus a few new ones. We'll get the docs updated ASAP!

**Comment by bobbyg603** [comment]
Hi @shehan-mark the documentation has been updated, please let us know if you need any help using the plugin! We can be reached via an email to support@bugsplat.com or via our [in-app chat](https://bugsplat.com).

**Comment by shehan-mark** [comment]
> Hi @shehan-mark the documentation has been updated, please let us know if you need any help using the plugin! We can be reached via an email to [support@bugsplat.com](mailto:support@bugsplat.com) or via our [in-app chat](https://bugsplat.com).

Thank you for the quick update and response. I will have a look and try again. :)
