### ISSUE TITLE
Unable to cook - demo content has errors

### ISSUE THREAD

**Issue by highlyunavailable** [BugSplat-Git/bugsplat-unreal#39]
I'm unable to cook my version of 4.26 with the BugSplat plugin without deleting the Content folder.

```
  LogAssetRegistry: Error: Package ../../../ShooterGame/Plugins/BugSplat/Content/UI/W_BugSplatButton.uasset has newer custom version of FortniteMain
  LogAssetRegistry: Error: Package ../../../ShooterGame/Plugins/BugSplat/Content/UI/W_BugSplatDemo.uasset has newer custom version of FortniteMain
```

I get the above error when using it. I can't just resave the assets either, they don't show up in the content browser at all - I can see the other plugin content, just not those widgets.

**Comment by bobbyg603** [comment]
Hi @highlyunavailable unfortunately the sample for this project is only available in Unreal 5.0 and later. The plugin should work just fine in 4.26 however.

**Comment by bobbyg603** [comment]
Ah, interesting, I'm sorry I misunderstood. I'll see what we can do...

**Comment by highlyunavailable** [comment]
Yeah... I'd suggest having a demo project and then leave all content out of the plugin. It doesn't seem like I need the plugin though as I can run sendpdbs manually, and it doesn't help with CI all that much (no commandlet to update the crash reporter URL, no auto update of crash reporter URL on postbuild that can see) so I'm probably not going to even use it. I also can't get the crash reporter URL to update from the editor (there's no ini file for packed builds), and it doesn't seem to update the global crash report URL either but that's a different issue.

**Comment by bobbyg603** [comment]
Not taking any action here, UE4 developers can work around this by deleting the demo content.
