### ISSUE TITLE
Replace SendPdbs with Symbol Upload

### ISSUE THREAD

**Issue by bobbyg603** [BugSplat-Git/bugsplat-unreal#43]
And remove BugSplatUser and BugSplatPassword.

**Comment by ariffammobox** [comment]
Does `SendPdbs.exe` no longer supported? We are getting `Http Request failed! {"message":"Empty dbgId not supported"}` errors.

**Comment by bobbyg603** [comment]
@ariffammobox SendPdbs is deprecated but should still work. Please email support@bugsplat.com.
